# 1. Numpy 
Numpy is a powerful Python module that should be in the toolbelt of any AI/Deep learning practitioner. It provides functions and data structures that allow fast, efficient manipulation of mathematical structures like matrices and vectors. It represents these structures internally using Numpy arrays, which are like Python Lists, but highly optimised for calculations on large amounts of numerical data. Let's import this module now.

Numpy arrays are almost the exact same as Pytorch Tensors, which you will have heard about by now. The only difference is that Pytorch Tensors can be operated on by the GPU; Numpy array operations are always performed by the CPU.  

In [107]:
import numpy as np

### 1.1.1 Array creation
Numpy arrays can be created in a few different ways. Common ones are:
1. Instantiated using values from a normal Python list
2. Filled with sequential values upto a target number
3. Filled with a specific value
4. Filled with random values (various random distributions available) - see https://numpy.org/doc/stable/reference/random/index.html

For a full list of array creation routines, please see: https://numpy.org/doc/stable/reference/routines.array-creation.html


In [108]:
#Array creation from python list
ary = np.array([1,2,3,4,5,6,85,48,5,4,87,4,87,8])
ary

array([ 1,  2,  3,  4,  5,  6, 85, 48,  5,  4, 87,  4, 87,  8])

In [109]:
#Array creation with sequential values 
ary = np.arange(0,20,2)
ary

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [110]:
#Array creation with random values
ary = np.random.randint(0,20 ,10)
ary



array([14, 14,  0,  5, 17,  8, 14,  3,  2, 11])

In [111]:
ary = np.random.rand(20)
print(ary)

[0.63124532 0.69118453 0.66150662 0.69144602 0.35742224 0.59165431
 0.59335465 0.70673021 0.74669195 0.20595507 0.57889041 0.77930265
 0.95135927 0.9928028  0.26921401 0.44039613 0.84760659 0.73367524
 0.43705998 0.44766124]


In [112]:
#Array filled with the same specific value
ary = np.zeros(10)
ary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [113]:
ary = np.ones(10)
ary

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
ary = np.zeros(10)
ary.fill(256)
ary

array([256., 256., 256., 256., 256., 256., 256., 256., 256., 256.])

### 1.1.2 Reshaping arrays

One of the many things that set Numpy arrays apart from Python lists is their `reshape` method. This allows you to define the number of dimensions that the structure represented by the array has. For example, the array `np_from_list` that we have just defined is just a flat list of numbers at the moment. `reshape` helps us represent it as a 2D data structure (a matrix). Keep in mind that the shape that you put into this method must agree with the number of elements in the array. In our example, the array has 10 elements, so acceptable shapes include:
* 5, 2
* 2, 5
* 1, 10
* 10, 1

In [118]:
res = ary.reshape((5,2))
print(f"{res}\n\n{res.shape}") 

[[256. 256.]
 [256. 256.]
 [256. 256.]
 [256. 256.]
 [256. 256.]]

(5, 2)


In [119]:
res_2 = ary.reshape((10,1))
print(f"{res_2}\n\n{res_2.shape}") 

array([[256.],
       [256.],
       [256.],
       [256.],
       [256.],
       [256.],
       [256.],
       [256.],
       [256.],
       [256.]])

In [ ]:
"""
You can also pass a desired shape into the array creation function to instantiate
an array with a pre-defined shape
"""


'\nYou can also pass a desired shape into the array creation function to instantiate\nan array with a pre-defined shape\n'

### 1.1.3 Exercises

In [ ]:
# Create a Numpy array A that contains the integers from 0 - 31 (32 elements long)
A = np.array([x for x in range (0,32)])
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [ ]:
# Create a Numpy array B that contains 12 random numbers between 0 and 1
B = np.random.random(size=12)
print(B)

[0.78958748 0.09042013 0.13311834 0.31587079 0.09386138 0.5546081
 0.15862536 0.67365707 0.88500068 0.27093863 0.45591731 0.19332153]


In [ ]:
# Turn A into a 2d matrix of shape (8, 4) - 8 rows, 4 columns
A = A.reshape((8,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
# Turn B into a 2d matrix of shape (4, 3)
B = B.reshape ((4,3))
print(B)

[[0.78958748 0.09042013 0.13311834]
 [0.31587079 0.09386138 0.5546081 ]
 [0.15862536 0.67365707 0.88500068]
 [0.27093863 0.45591731 0.19332153]]


## 1.2 Array operations
Once you have created an array, there are various operations you may want to perform on them. We'll go through some of the most common ones in the next few cells.

### 1.2.1 Binary operators
Similar to normal counting numbers, Numpy arrays can be used as arguments to binary arithmetic operators like `*` (multiplication), `+` (addition), `-`(subtraction) and `/`(division). However, these can only be applied to arrays under certain conditions:
1. The arrays have the same shape, OR
2. The operation is between an array and a scalar, OR
3. The operations is between 2 arrays of different shapes that can be "broadcast" together - more on this later

These operations are applied **element-wise** meaning each element in the array is combined with its corresponding element at the same position in the other array

In [ ]:
# Addition with a scalar


In [ ]:
# Subtraction with another array of same shape


In [ ]:
# Multiplication with another array of same shape


In [ ]:
# Division by a scalar


### 1.2.2 Broadcasting
As long as an array's dimensions are compatible with their counterparts in the other array, they can be "broadcasted" together. This means that numpy will 'stretch' the smaller dimension along its axis so that element-wise operations can be applied between them. In general, 2 arrays can be broadcast together if each dimension in one array is compatible with its counterpart in the other array. Dimensions are compatible if they are equal or one of them is equal to 1. The dimension of size 1 is expanded to fit the size of its counterpart [https://numpy.org/doc/stable/user/basics.broadcasting.html]

In [ ]:
# Similarly, we can also broadcast an array of shape (1, 2) along B's vertical axis



### 1.2.3 Array products
Contrary to the `*` operator, which performs element-wise multiplication between the arrays, `np.matmul` is the matrix product of the arrays.

### 1.2.4 Exercises

In [ ]:
# Divide your array B by the number 2.5. Store the result in a variable C
C = ...
print(C)

Ellipsis


In [ ]:
# Create a new array filled with -1. The array must have the same shape as B. Store the result in a variable D
D = ...
print(D)

Ellipsis


In [ ]:
# Multiply this new array ELEMENT-WISE with B and store the result in a variable called E.
E = ...
print(E)

Ellipsis


In [ ]:
# Consider the intermediate array below. 
intermediate_arr = np.arange(4).reshape(2, 2)
print(intermediate_arr)

[[0 1]
 [2 3]]


In [ ]:
# Try and multiply it with D element-wise. What happens? What could 
# you do to make this multiplication work? (hint: try and make
# the intermediate array broadcastable to C)
intermediate_arr = ...
F = ...
print(F)

Ellipsis


## 1.3 Functions
Another useful thing we might want to do with an array is to apply a function to each element. Generally speaking, it is best to use the built-in Numpy functions to work on numpy arrays instead of defining your own. This is because Numpy functions are highly optimised for speed, which is important when working with large amounts of data. Chances are, whatever kind of mathematical operation you want to perform on a Numpy array is already built in. See below for a full list:  
https://numpy.org/doc/stable/reference/routines.math.html  

### 1.3.1 Element-wise functions
Common uses are applying trig functions to an array of values:

In [ ]:
import matplotlib.pyplot as plt

def simple_plot(x, y, label):
    plt.plot(x, y)
    plt.suptitle(label)
    plt.show()

    

# Element-wise functions: 


### 1.3.2 Reduce functions
These are applied along the selected axis, consume all the elements and reduce the axis down to 1 element. If no axis is specified, the function is applied to the whole array, and reduces it to a scalar

In [ ]:
# Max, mean minimun functions:


### 1.3.3 Exercises


In [ ]:
# Have a look at the trigonometric functions listed in the official numpy documentation: 
# https://numpy.org/doc/stable/reference/routines.math.html
# Pick any element-wise function that takes 1 numpy array as an argument and apply it to the following
# array. store the result in a variable called Ys
Xs = np.arange(-2*np.pi, 2*np.pi, 0.1)
Ys = ...
print(Ys)

Ellipsis


In [ ]:
# Call our previously-defined simple plot function and display your result! Give the plot a suitable title
...

In [ ]:
# Use a suitable Numpy reduce function to find the maximum value of your function's result
max_val = ...
print(max_val)

Ellipsis


## 1.4 numpy.where
This allows us to conditionally modify the elements of an array, which can be useful for tasks like thresholding or masking.

### 1.4.1 Exercises


In [ ]:
# Create a Numpy array of shape (10, 5) and fill it with random values between 0 and 1. Store it in a variable called J
J = ...
print(J)

Ellipsis


In [ ]:
# Conditionally modify the array such that numbers below 0.5 are replaced with 0 and numbers above 
# or equal to 0.5 are replaced with 1. Store the result in a variable called K
K = ...
print(K)

Ellipsis


## 1.5 Practical example

Putting everything together for a practical example, and visulalise the output of some Numpy operations

In [ ]:
# Defining some helper functions
def plot_point(point):
    plt.rcParams["figure.figsize"] = [3.50, 3.50]
    plt.rcParams["figure.autolayout"] = True
    x = point[0]
    y = point[1]
    
    lims = 3
    fig = plt.figure()
    ax = fig.add_subplot(111)
    plt.xlim(-lims, lims)
    plt.ylim(-lims, lims)
    plt.grid()
    ax.plot(x, y, marker="o", markersize=7, markeredgecolor="black", markerfacecolor="red")
    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_color('none')
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_color('none')
    plt.show()



# This function returns an np array that describes a 2d rotation 
# matrix [https://www1.udel.edu/biology/rosewc/kaap686/notes/matrices_rotations.pdf]. 
# These kinds of structures are often used in computer graphics to rotate and translate points in space
def get_rot_clockwise_matrix(angle):
    return np.array([
        [ np.cos(angle), np.sin(angle)],
        [-np.sin(angle), np.cos(angle)]
    ])

In [ ]:
# Create a random 2-element array containing values from 0 - 1. Assign this array to a variable `p`
p = ...
print(p)

Ellipsis


In [ ]:
# Use scalar multiplication to double the value of the elements in `p`. Assign the result back to `p`
p = ...
print(p)

Ellipsis


In [ ]:
# Reshape `p` to be (2, 1), assign the result to `p` and plot the point.
p = ...


In [ ]:
# We will now rotate this point about the origin of the plot using the funciton we defined above
# This cell is just some setup for the rest of the exercise, just run it once
min_angle = np.pi/2 # 90 degrees
max_angle = np.pi   # 180 degrees
angle = np.random.uniform(min_angle, max_angle) # get a random angle between 90 and 180 degrees
print(np.degrees(angle)) # print the angle in degrees so we can check the rotation is correct!

176.45905851975013


In [ ]:
# Call the previously-defined roation matrix function with the angle. Assign the result to 
# a variable called `rot90`
rot90 = ...


In [ ]:
# Apply a matrix multiplication operation between rot90 and p. assign the result back to p and plot it.
p = ...


In [ ]:
# Create an array named `translation` which has the same shape as `p`, and fill it with 2's
translation = ...
print(translation)

Ellipsis


In [ ]:
# Add this result to p and plot it!
p = ...
